# Generated by Django 2.2 on 2022-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcontent',
            name='collapse_num',
            field=models.CharField(default='test', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqcontent',
            name='heading_num',
            field=models.CharField(default='collapsetest', max_length=12),
            preserve_default=False,
        ),
    ]
